### ISSUE TITLE
Thanks! Does it fit in Free Colab? 

### ISSUE THREAD

**Issue by amrrs** [openlm-research/open_llama#1]
Hey Thanks very much for the effort. Looking at the released model size, Wondering if it can fit in Free Colab?

**Comment by young-geng** [comment]
The model architecture and size is the same as LLaMA 7B, so if the original LLaMA 7B fits, our model should fit as well. If not, we are also working on a smaller LLaMA 3B model, which we will release a preview checkpoint soon.

**Comment by sw-yx** [comment]
@amrrs if you manage to get it working in a Colab i'd be very keen too!

**Comment by curiousily** [comment]
I made a video on how to run it in Google Colab (it fits in T4 GPU): 
https://www.youtube.com/watch?v=1NOPciKuQb8

Hope that helps!

**Comment by young-geng** [comment]
We've just released a checkpoint for our 3B model and that should definitely fit in colab.
