### ISSUE TITLE
Is the 1T tokens completed?

### ISSUE THREAD

**Issue by alimadelshin** [openlm-research/open_llama#36]
is the 1T training completed or is there any issues with the training?

**Comment by young-geng** [comment]
The 1T token training is done for the 7b model, but we are waiting for the 3b model to complete so we can release them together. The anticipated release is next Monday.

**Comment by young-geng** [comment]
We've just released the 1T token final version for the 3B and 7B models. We've also released a 600B token preview for the 13B model.
