### ISSUE TITLE
compatibility with llama.cpp

### ISSUE THREAD

**Issue by nivibilla** [openlm-research/open_llama#38]
Hey, first of all, amazing work. Thanks for building an open llama model. As the title suggests, I would like to know if this model could be compatible with llamacpp

Thanks

**Comment by codesoap** [comment]
Works flawlessly with OpenAlpaca, but I strongly assume this means OpenLLaMa will work as well.

**Comment by nivibilla** [comment]
Amazing, then we can take advantage of all the tools in llama.cpp. Especially the M1 gpu inference. I get 88ms per token on guanaco 13b on my MacBook. which is quite fast considering how big the model is.
