### ISSUE TITLE
LLaMA 3B configuration

### ISSUE THREAD

**Issue by LamOne1** [openlm-research/open_llama#49]
Hello,

first I'd like to thank you for providing these weights! amazing work!

I want to know what is the configuration of LLaMA3B, specifically, what are the numbers of 1)layers, 2)heads, 3)dimension?

**Comment by LamOne1** [comment]
Hi @young-geng,
I created the architecture using lit-llama by lightning, but there was a problem, the dimension of the produced layer "mlp.gate_proj.weight" or "mlp.c_fc1.weight" is 8704, while in the chechpoint it's 8640.

I appreciate your help.

**Comment by young-geng** [comment]
The 3B size is not a standard LLaMA size, so different libraries have the freedom to define their own architectures.
