### ISSUE TITLE
Corpora for Ukrainian

### ISSUE THREAD

**Issue by egorsmkv** [openlm-research/open_llama#5]
Hello.

There is  a corpora call Ubercorpus for Ukrainian you can add to the project: https://lang.org.ua/en/corpora/#anchor4

In a few days will be UNLP, an event from Ukrianian NLP community and there will be presented the second version of the corpus with larger size.

**Comment by podarok** [comment]
Would be nice to have Ukrainian Ubercorpus to OpenLLama
