### ISSUE TITLE
Tranlsated to another language.

### ISSUE THREAD

**Issue by dsdanielpark** [openlm-research/open_llama#55]
I can retrain open_llama, which is trained under the Apache License, in Korean. Could you please guide me on how to obtain the dataset and provide detailed instructions for the training process? I would like to translate the dataset into Korean and retrain the model accordingly. Thank you for your amazing project once again, and I appreciate any guidance you can provide.

**Comment by xingenju** [comment]
> I can retrain open_llama, which is trained under the Apache License, in Korean. Could you please guide me on how to obtain the dataset and provide detailed instructions for the training process? I would like to translate the dataset into Korean and retrain the model accordingly. Thank you for your amazing project once again, and I appreciate any guidance you can provide.

Have you started to re-train the Korean version?
