### ISSUE TITLE
Maybe a link on how to set it up ?

### ISSUE THREAD

**Issue by PGTBoos** [openlm-research/open_llama#6]
Might be nice to try this, but how does one set it up in a python jupyter environment ?. 
 (a working step by step would be nice, or an example notebook)

I'm no newbie but never had the time to spend a few days into LLM's. 
if a 3080ti can run it , ib be fun to give it a try.

**Comment by young-geng** [comment]
Thanks for the suggestion! Since we train this with JAX using our EasyLM framework, we have [detailed documentation for using it with EasyLM](https://github.com/young-geng/EasyLM/blob/main/docs/llama.md). As for using it with PyTorch, unfortunately we weren't able to experiment much as our compute resources are on TPU.

**Comment by PGTBoos** [comment]
Ok thanks if you would like to draw much attention with it you might reconsider this. (a lot more people would be able to test it, not many people i know of have TPU's these days).
________________________________
Van: Xinyang (Young) Geng ***@***.***>
Verzonden: donderdag 4 mei 2023 00:02
Aan: openlm-research/open_llama ***@***.***>
CC: PGTBoos ***@***.***>; Author ***@***.***>
Onderwerp: Re: [openlm-research/open_llama] Maybe a link on how to set it up ? (Issue #6)


Thanks for the suggestion! Since we train this with JAX using our EasyLM framework, we have detailed documentation for using it with EasyLM<https://github.com/young-geng/EasyLM/blob/main/docs/llama.md>. As for using it with PyTorch, unfortunately we weren't able to experiment much as our compute resources are on TPU.

**Comment by young-geng** [comment]
You can also use the JAX version on GPU. That's how we test it locally.
