### ISSUE TITLE
Do you mind providing the exact command or script used to produce the evaluation results?

### ISSUE THREAD

**Issue by yxchng** [openlm-research/open_llama#60]

**Comment by young-geng** [comment]
Please follow the [serving](https://github.com/young-geng/EasyLM/blob/main/docs/serving.md) and [evaluation](https://github.com/young-geng/EasyLM/blob/main/docs/evaluation.md) documentation of EasyLM to run the evaluation we did. A much simpler way is to use [lm-eval-harness](https://github.com/EleutherAI/lm-evaluation-harness). Just remember to turn off the fast tokenizer as [transformers fast tokenizer has a bug](https://github.com/huggingface/transformers/issues/24233),
