### ISSUE TITLE
openlm-research/open_llama_13b_easylm cannot be downloaded

### ISSUE THREAD

**Issue by leweex95** [openlm-research/open_llama#66]
I attempted to download the aforementioned model from: https://huggingface.co/openlm-research/open_llama_13b_easylm but it fails with the following error:

```
OSError: openlm-research/open_llama_13b_easylm does not appear to have a file named config.json. Checkout 'https://huggingface.co/openlm-research/open_llama_13b_easylm/main' for available files.
```

Code to reproduce:

```
model_id = "openlm-research/open_llama_13b_easylm"
model_name = model_id.split("/")[1]

model = pipeline(model=model_id)
model.save_pretrained(f"./models/{model_name}")
```

I expect the model to be downloadable locally for use in downstream NLP tasks. Noteworthy is that on the [website](https://huggingface.co/openlm-research/open_llama_13b_easylm) it is indicated that 0 people downloaded this model over the past month. 

With the above script, I can easily fetch other models such as `"openlm-research/open_llama_13b"`:

```
model_id = "openlm-research/open_llama_13b"
model_name = model_id.split("/")[1]

model = pipeline(model=model_id)
model.save_pretrained(f"./models/{model_name}")
```

Looking at: https://huggingface.co/openlm-research/open_llama_13b_easylm/tree/main it seems that the file doesn't have a torch bin file. However, https://huggingface.co/openlm-research/open_llama_13b/tree/main has those .bin files.

Could you please tell me if this behavior is by design and if so, how I can fetch the model from HuggingFace?

**Comment by young-geng** [comment]
`open_llama_13b_easylm` is intended to be used with our own JAX based [EasyLM](https://github.com/young-geng/EasyLM) framework. It is not compatible with the transformers pytorch implementation.  To use the pytorch version, you need to use `open_llama_13b`. This is documented in the readme of this project.
