### ISSUE TITLE
What precision is used for model pre-training?

### ISSUE THREAD

**Issue by haozhouamzn** [openlm-research/open_llama#67]
Hello.

I am wondering what kind of precision strategy is applied during the pre-training?

Is it fp32, fp16, bf16 or mixed precision? 

Thank you in advance

**Comment by gjmulder** [comment]
WHat was the answer, pls?

**Comment by haozhouamzn** [comment]
> WHat was the answer, pls?

Full fp32 https://github.com/young-geng/EasyLM/issues/71
