### ISSUE TITLE
 Any plan for OpenLLaMA-65B？

### ISSUE THREAD

**Issue by JingxinLee** [openlm-research/open_llama#71]
Do you have a plan for releasing OpenLLaMA-65B？ Maybe met the GPUs  amount bottleneck? Thanks

**Comment by young-geng** [comment]
Unfortunately we don't have the compute resources to do that.

**Comment by JingxinLee** [comment]
> Unfortunately we don't have the compute resources to do that.

So how many H100/H800 GPUs do you need to train a OpenLLaMA-65B model?  May I ask the minimum number?

**Comment by young-geng** [comment]
I believe you will need at least 1000 of them to finish the training within a month.

**Comment by JingxinLee** [comment]
If I don't mind the amount of month to train, for example, I have 5 months to train a 65B model, can I say that I need at least 1000/5=200 GPUs? If I have 10 months to train, can I say I need at least 1000/10=100 GPUs? Thanks

**Comment by young-geng** [comment]
That sounds about right.
