### ISSUE TITLE
Updates on 20b version?

### ISSUE THREAD

**Issue by pikalover6** [openlm-research/open_llama#73]
Do you plan on releasing the v1 20b model?

**Comment by gjmulder** [comment]
Do you mean  the llama 33 billion weight model? If so, given it takes three times as long (twice the size and 1.4B tokens) to train as the 13b I suspect not.

**Comment by pikalover6** [comment]
> Do you mean the llama 33 billion weight model? If so, given it takes three times as long (twice the size and 1.4B tokens) to train as the 13b I suspect not.

No, the creators have said that they trained a 20b model on discord/Twitter.

**Comment by young-geng** [comment]
I think the 20B model is trained by Stability AI, and we are not involved in that, so I wouldn't consider that part of this project.
