### ISSUE TITLE
Pre-training Data for OpenLLaMA 7Bv2

### ISSUE THREAD

**Issue by guoxiaobo96** [openlm-research/open_llama#77]
Thank you for your great job of the V2 model. It really helps me a lot. However, I have a question about the pre-training data of the V2. 

In readme, you say the model "is trained on a mixture of Falcon refined-web dataset, mixed with the starcoder dataset and the wikipedia, arxiv and books and stackexchange from RedPajama." I am wondering is it possible to know the exact percent of each dataset, any new pre-process because of the new sub datasets and other details. Or is it possible for you to release the new pre-training data/ the code of creating the pre-training data.

**Comment by young-geng** [comment]
We simply combined all the parts together and shuffled the examples. Everything is trained for 1 epoch.
