### ISSUE TITLE
Question about data ratio

### ISSUE THREAD

**Issue by siriusctrl** [openlm-research/open_llama#84]
Hi there, thanks for the amazing work. Do you mind sharing the data ratio (like XGen) for reproducing the pre-training results?
<img width="953" alt="image" src="https://github.com/openlm-research/open_llama/assets/26541600/7f1c4f52-69c1-4fe9-a594-ba088adc5ca8">

**Comment by itsliupeng** [comment]
I suppose it's similar to the use of LLama thesis, isn't it?
![image](https://github.com/openlm-research/open_llama/assets/680843/911d0385-cffa-4a3f-bff7-9ae715f98aa5)

**Comment by siriusctrl** [comment]
> I suppose it's similar to the use of LLama thesis, isn't it? ![image](https://user-images.githubusercontent.com/680843/256775305-911d0385-cffa-4a3f-bff7-9ae715f98aa5.png)

Thanks for sharing, quoting from the README
> is trained on a mixture of [Falcon refined-web dataset](https://huggingface.co/datasets/tiiuae/falcon-refinedweb), mixed with the [starcoder dataset](https://huggingface.co/datasets/bigcode/starcoderdata), and the wikipedia, arxiv and books and stackexchange from [RedPajama](https://huggingface.co/datasets/togethercomputer/RedPajama-Data-1T).

Just want to be clear, we are using random samples from Falcon refined-web dataset to replace CC+C4, and starcoder to  replace Github. But how the sampling prop changed in this case as the released version of falcon refined web is actually small in size compare to what used in Llama? Can I assume that OpenLlama go through Falcon dataset with larger epochs?

**Comment by young-geng** [comment]
For the v1 model, we simply combined the partitions of RedPajama. We did not oversample any partitions. For the v2 model, we simply replaced the CC part of RedPajama with Falcon refined-web and the GitHub part with StarCoder data. We also didn't use any oversampling for the v2 model. So in short, for both the v1 and v2 models, we never train for more than 1 epoch on any subsets.

**Comment by itsliupeng** [comment]
Thank you for your response. However, after using the OpenLlama tokenizer on the [public Falcon dataset](https://huggingface.co/datasets/tiiuae/falcon-refinedweb), I only obtained 575B tokens. If I just train for one epoch, I can't achieve a total of 1TB tokens.

**Comment by young-geng** [comment]
> Thank you for your response. However, after using the OpenLlama tokenizer on the [public Falcon dataset](https://huggingface.co/datasets/tiiuae/falcon-refinedweb), I only obtained 575B tokens. If I just train for one epoch, I can't achieve a total of 1TB tokens.

That's why we have the wiki, books, arxiv, stackexchange from RedPajama and StarCoder data in v2.

**Comment by itsliupeng** [comment]
> > Thank you for your response. However, after using the OpenLlama tokenizer on the [public Falcon dataset](https://huggingface.co/datasets/tiiuae/falcon-refinedweb), I only obtained 575B tokens. If I just train for one epoch, I can't achieve a total of 1TB tokens.
> 
> That's why we have the wiki, books, arxiv, stackexchange from RedPajama and StarCoder data in v2.

In the RedPajama dataset, the content from Wiki, books, arXiv, and StackExchange is quite limited. Hence, did you utilize the entire StarCoder dataset instead of just the 4.5%  as mentioned in the Llama paper?"

**Comment by young-geng** [comment]
We used the entire starcoder dataset. Everything was trained for 1 epoch.

**Comment by itsliupeng** [comment]
Thanks, i see.
