### ISSUE TITLE
It seems like I can't use beluga2 in m2max. I'm getting the following error.

### ISSUE THREAD

**Issue by mudman21** [openlm-research/open_llama#85]
`ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.`

**Comment by young-geng** [comment]
I'm not sure if this is the right GitHub project to get help with this question, as this is the project page for OpenLLaMA, and we are not familiar with the beluga2 project.
